#=====  Spring settings  =====#
spring:
  application:
    name: activiti
  jackson:
    time-zone: GMT+8
#=====  Mysql settings  =====#
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.12.2.116:3306/camunda?useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=GMT%2B8
    username: goldwind
    password: goldwind
##多彩输出
#  output:
#    ansi:
#      enabled: detect
#  mvc:
#    view:
#      prefix: /page/
#      suffix: .html
#=====   mybatis settings   =====#
#mybatis:
#  mapper-locations: classpath:mappers/*.xml
#  type-aliases-package: com.donwae.market.entity

##=====   log settings   =====#
##输出日志到文件
#logging:
#  file: /Users/goldwindzty/Logs/muskmelon/log-info.log
#  pattern:
#    level: com.donwae.market.*=debug
mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 9080

#=====   camunda settings   =====#
camunda:
  bpm:
    auto-deployment-enabled: true
    admin-user:
      id: goldwind
      password: goldwind
      first-name: goldwind
    filter:
      create: All Task


logging:
  config: classpath:logback-dev.xml