#=====  Spring settings  =====#
spring:
  application:
    name: muskmelon
#=====  Mysql settings  =====#
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DONWAEDB?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: donwae
    password: donwae1234
#多彩输出
  output:
      ansi:
        enabled: detect

#=====   mybatis settings   =====#
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.donwae.market.entity

#=====   log settings   =====#
#输出日志到文件
logging:
  file: /Users/goldwindzty/Logs/muskmelon/log-info.log
  pattern:
    level: com.donwae.market.*=debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

server:
  port: 8011